name: sraFramework CI

on:
  - push

env:
  RF_CONFIG: template.yaml
  RF_TAG: demo

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Execute Test Case
        run: |
          docker run --shm-size=1g --rm -i bxwill/robotframework:py-chrome-allure bash -c "./sraf-cmd --config config/${RF_CONFIG} --tag ${RF_TAG}"
